// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/orders/orders.proto

package orders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_orders_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    int32                  `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_orders_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_orders_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_proto_orders_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_proto_orders_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{4}
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_proto_orders_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    int32                  `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_orders_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderRequest) GetCustomerId() int32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_proto_orders_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type FulfillOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillOrderRequest) Reset() {
	*x = FulfillOrderRequest{}
	mi := &file_proto_orders_orders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillOrderRequest) ProtoMessage() {}

func (x *FulfillOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillOrderRequest.ProtoReflect.Descriptor instead.
func (*FulfillOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{8}
}

func (x *FulfillOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FulfillOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillOrderResponse) Reset() {
	*x = FulfillOrderResponse{}
	mi := &file_proto_orders_orders_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillOrderResponse) ProtoMessage() {}

func (x *FulfillOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillOrderResponse.ProtoReflect.Descriptor instead.
func (*FulfillOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{9}
}

func (x *FulfillOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_proto_orders_orders_proto protoreflect.FileDescriptor

const file_proto_orders_orders_proto_rawDesc = "" +
	"\n" +
	"\x19proto/orders/orders.proto\x12\x06orders\"F\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xbb\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x05R\n" +
	"customerId\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.orders.OrderItemR\x05items\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"7\n" +
	"\x10GetOrderResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.orders.OrderR\x05order\"\x13\n" +
	"\x11ListOrdersRequest\";\n" +
	"\x12ListOrdersResponse\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.orders.OrderR\x06orders\"^\n" +
	"\x12CreateOrderRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\x05R\n" +
	"customerId\x12'\n" +
	"\x05items\x18\x02 \x03(\v2\x11.orders.OrderItemR\x05items\":\n" +
	"\x13CreateOrderResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.orders.OrderR\x05order\"%\n" +
	"\x13FulfillOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\";\n" +
	"\x14FulfillOrderResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.orders.OrderR\x05order2\xa5\x02\n" +
	"\fOrderService\x12=\n" +
	"\bGetOrder\x12\x17.orders.GetOrderRequest\x1a\x18.orders.GetOrderResponse\x12C\n" +
	"\n" +
	"ListOrders\x12\x19.orders.ListOrdersRequest\x1a\x1a.orders.ListOrdersResponse\x12F\n" +
	"\vCreateOrder\x12\x1a.orders.CreateOrderRequest\x1a\x1b.orders.CreateOrderResponse\x12I\n" +
	"\fFulfillOrder\x12\x1b.orders.FulfillOrderRequest\x1a\x1c.orders.FulfillOrderResponseB\x1dZ\x1borders-service/proto/ordersb\x06proto3"

var (
	file_proto_orders_orders_proto_rawDescOnce sync.Once
	file_proto_orders_orders_proto_rawDescData []byte
)

func file_proto_orders_orders_proto_rawDescGZIP() []byte {
	file_proto_orders_orders_proto_rawDescOnce.Do(func() {
		file_proto_orders_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orders_orders_proto_rawDesc), len(file_proto_orders_orders_proto_rawDesc)))
	})
	return file_proto_orders_orders_proto_rawDescData
}

var file_proto_orders_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_orders_orders_proto_goTypes = []any{
	(*OrderItem)(nil),            // 0: orders.OrderItem
	(*Order)(nil),                // 1: orders.Order
	(*GetOrderRequest)(nil),      // 2: orders.GetOrderRequest
	(*GetOrderResponse)(nil),     // 3: orders.GetOrderResponse
	(*ListOrdersRequest)(nil),    // 4: orders.ListOrdersRequest
	(*ListOrdersResponse)(nil),   // 5: orders.ListOrdersResponse
	(*CreateOrderRequest)(nil),   // 6: orders.CreateOrderRequest
	(*CreateOrderResponse)(nil),  // 7: orders.CreateOrderResponse
	(*FulfillOrderRequest)(nil),  // 8: orders.FulfillOrderRequest
	(*FulfillOrderResponse)(nil), // 9: orders.FulfillOrderResponse
}
var file_proto_orders_orders_proto_depIdxs = []int32{
	0,  // 0: orders.Order.items:type_name -> orders.OrderItem
	1,  // 1: orders.GetOrderResponse.order:type_name -> orders.Order
	1,  // 2: orders.ListOrdersResponse.orders:type_name -> orders.Order
	0,  // 3: orders.CreateOrderRequest.items:type_name -> orders.OrderItem
	1,  // 4: orders.CreateOrderResponse.order:type_name -> orders.Order
	1,  // 5: orders.FulfillOrderResponse.order:type_name -> orders.Order
	2,  // 6: orders.OrderService.GetOrder:input_type -> orders.GetOrderRequest
	4,  // 7: orders.OrderService.ListOrders:input_type -> orders.ListOrdersRequest
	6,  // 8: orders.OrderService.CreateOrder:input_type -> orders.CreateOrderRequest
	8,  // 9: orders.OrderService.FulfillOrder:input_type -> orders.FulfillOrderRequest
	3,  // 10: orders.OrderService.GetOrder:output_type -> orders.GetOrderResponse
	5,  // 11: orders.OrderService.ListOrders:output_type -> orders.ListOrdersResponse
	7,  // 12: orders.OrderService.CreateOrder:output_type -> orders.CreateOrderResponse
	9,  // 13: orders.OrderService.FulfillOrder:output_type -> orders.FulfillOrderResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_orders_orders_proto_init() }
func file_proto_orders_orders_proto_init() {
	if File_proto_orders_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orders_orders_proto_rawDesc), len(file_proto_orders_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orders_orders_proto_goTypes,
		DependencyIndexes: file_proto_orders_orders_proto_depIdxs,
		MessageInfos:      file_proto_orders_orders_proto_msgTypes,
	}.Build()
	File_proto_orders_orders_proto = out.File
	file_proto_orders_orders_proto_goTypes = nil
	file_proto_orders_orders_proto_depIdxs = nil
}
